import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
const [root, php, ext, token]=process.argv.slice(2);
const base='http://127.0.0.1:18874';
const fixture=mode=>JSON.parse(execFileSync(php,['-d',`extension_dir=${ext}`,'-d','extension=pdo_sqlite','tests/public-flow-fixture.php',root,mode],{encoding:'utf8'})||'null');
function client(){let cookie='';return async function request(path,data){const response=await fetch(base+path,{method:data?'POST':'GET',headers:{Cookie:cookie,...(data?{'Content-Type':'application/x-www-form-urlencoded'}:{})},body:data?new URLSearchParams(data):undefined,redirect:'manual'});if(response.headers.get('set-cookie'))cookie=response.headers.get('set-cookie').split(';')[0];const body=await response.text();assert(!/Fatal error|Warning:|Parse error/.test(body),body.slice(0,1000));return {body,status:response.status,location:response.headers.get('location')};};}
const field=(html,name)=>{const escaped=name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const match=html.match(new RegExp(`name="${escaped}"[^>]*value="([^"]*)"`));assert(match,`Missing field ${name}`);return match[1];};
const person=client(), admin=client(), interviewer=client();
assert.equal((await person('/index.php?page=interview_report&id=1')).status,302,'report requires authentication');
const reviewer=client();
async function assess(name,mobile,correct){let page=await person('/h5.php?m=apply&t='+token);let response=await person('/h5.php?m=apply&t='+token+'&step=verify',{csrf:field(page.body,'csrf'),name,mobile});assert.equal(response.status,302);page=await person(response.location);assert(page.body.includes('自动测试专业题'));assert(!page.body.includes('不应出现在自动测评的简答题'));const data={csrf:field(page.body,'csrf'),idempotency_key:field(page.body,'idempotency_key'),gender:'男',birth_date:'2000-01-01',health:'健康',edu:'硕士',school_tier:'普通本科',major:'测试',title:'',politics:'群众',work_years:'12',prof_years:'12',group_co_years:'0',listed_co_years:'0',private_co_years:'0',work_bg:'测试',computer_skill:'熟练',language:'熟练','answers[base_1]':correct?'正确':'错误','answers[post_1][]':correct?'正确':'错误'};response=await person('/h5.php?m=apply&t='+token+'&step=submit',data);assert.equal(response.status,302);page=await person(response.location);assert(page.body.includes(correct?'100.0 / 100':'50.0 / 100'));assert(page.body.includes('<h2>测评成绩</h2>'));return page;}
let page=await person('/h5.php?m=apply&t=unified');assert(page.body.includes('请选择应聘岗位'));assert(!page.body.includes('name="mobile"'));
await assess('测试甲','13900000101',true);await assess('测试乙','13900000102',false);
page=await admin('/index.php?page=login');let response=await admin('/index.php?page=login',{csrf:field(page.body,'csrf'),username:'admin',password:'admin123'});assert.equal(response.status,302);
page=await admin('/index.php?page=interviews');assert(page.body.includes('创建面试场次'));
let arrangePage=await admin('/index.php?page=talent&tab=arrange');assert(arrangePage.body.includes('测试甲'));assert(!arrangePage.body.includes('测试乙'));
let eligible=JSON.parse((await admin('/index.php?page=interviews&action=eligible_candidates')).body);assert.equal(eligible.length,1);
fixture('above-boundary');assert.equal(JSON.parse((await admin('/index.php?page=interviews&action=eligible_candidates')).body).length,2,'60.1 must qualify');fixture('boundary');assert.equal(JSON.parse((await admin('/index.php?page=interviews&action=eligible_candidates')).body).length,1,'60 must not qualify');
response=await admin('/index.php?page=interviews&action=session_save',{csrf:field(page.body,'csrf'),submission_token:field(page.body,'submission_token'),post_id:'1',interview_date:new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Shanghai'}),time_range:'14:00-16:00',location:'测试室'});assert.equal(response.status,302);
page=await admin('/index.php?page=interviews');const csrf=field(page.body,'csrf');const sid=field(page.body,'session_id');
response=await admin('/index.php?page=interviews&action=assign_candidate_v2',{csrf,session_id:sid,registration_id:eligible[0].id,seq:'1'});assert.equal(response.status,302);assert.equal(fixture('inspect').assignments.length,1);
arrangePage=await admin('/index.php?page=talent&tab=arrange');assert(!arrangePage.body.includes('测试甲'));
let pendingReview=await admin('/index.php?page=talent&tab=final');assert(pendingReview.body.includes('测试甲'));assert(pendingReview.body.includes('等待面试完成'));assert(!pendingReview.body.includes('name="stage" value="final"'));
await admin('/index.php?page=talent&action=review',{csrf,result_id:'1',stage:'final',current:'interview',op:'pass'});assert.equal(fixture('inspect').results[0].review_status,'interview','unfinished interview cannot be approved');
fixture('boundary');await admin('/index.php?page=interviews&action=assign_candidate_v2',{csrf,session_id:sid,registration_id:'2',seq:'2'});assert.equal(fixture('inspect').assignments.length,1,'60 must be rejected by backend');
await admin('/index.php?page=interviews&action=assign_interviewer',{csrf,session_id:sid,user_id:'3',weight:'1'});
page=await admin('/index.php?page=talent_pool');assert(!page.body.includes('测试甲'));assert(!page.body.includes('测试乙'));
page=await interviewer('/h5.php?m=interview&t=unified');response=await interviewer('/h5.php?m=interview&t=unified&step=login',{csrf:field(page.body,'csrf'),real_name:'李四',mobile:'13800000002'});page=await interviewer(response.location);const scoreLink=page.body.match(/href="([^\"]*step=score[^\"]*)"/);assert(scoreLink,page.body);page=await interviewer('/h5.php'+scoreLink[1]);assert(page.body.includes('满分 100 分'));assert(page.body.includes('<span>100分</span>'));assert(page.body.includes('<span>20分</span>'));const action=page.body.match(/action="([^\"]*step=score)"/)[1];const scores={csrf:field(page.body,'csrf'),candidate_id:field(page.body,'candidate_id'),strengths:'好',risks:'无',recommendation:'recommend'};for(const dim of ['professional','experience','communication','logic','teamwork','learning','professionalism'])scores[`dims[${dim}]`]='4';response=await interviewer('/h5.php'+action,scores);assert.equal(response.status,302);
page=await reviewer('/index.php?page=login');response=await reviewer('/index.php?page=login',{csrf:field(page.body,'csrf'),username:'lisi',password:'admin123'});assert.equal(response.status,302);
for(const allowed of ['dashboard','talent','talent_pool','interview_results','password'])assert.equal((await reviewer('/index.php?page='+allowed)).status,200,allowed);
for(const forbidden of ['users','posts','questions','interviews','settings'])assert.equal((await reviewer('/index.php?page='+forbidden)).status,403,forbidden);
assert.equal((await reviewer('/index.php?page=dashboard&action=user_save',{})).status,403);
page=await reviewer('/index.php?page=talent&tab=final');assert(page.body.includes('测试甲'));assert(!page.body.includes('测评待处理'));response=await reviewer('/index.php?page=talent&action=review',{csrf:field(page.body,'csrf'),result_id:'1',stage:'final',current:'interview',op:'pass',note:'测试通过'});assert(response.location.includes('tab=final'));
page=await admin('/index.php?page=talent_pool');assert(page.body.includes('测试甲'));assert(!page.body.includes('测试乙'));assert.equal(fixture('inspect').fk.length,0);
const leader=client();page=await leader('/index.php?page=login');response=await leader('/index.php?page=login',{csrf:field(page.body,'csrf'),username:'oldleader',password:'test12345'});assert.equal(response.status,200);assert(response.body.includes('用户名或密码错误'));
page=await admin('/index.php?page=users');assert(!page.body.includes('value="leader"'));
assert(page.body.includes('value="interviewer"'));assert(page.body.includes('lisi'));assert(!page.body.includes('面试官维护'));
assert.equal((await admin('/index.php?page=interviewers')).location,'/index.php?page=users');assert.equal((await admin('/index.php?page=manual')).status,302);
page=await admin('/index.php?page=talent&tab=first');assert(!page.body.includes('测评待处理'));assert(page.body.includes('待安排面试'));
await assess('测试甲','13900000101',true);
assert.equal(fixture('inspect').results.length,3,'repeat assessment creates a new result');
page=await admin('/index.php?page=talent&tab=hired');
assert(page.body.includes('<th>面试分数</th><th>面试报告</th>'));
assert(page.body.includes('target="_blank" rel="noopener">查看报告'));
assert(page.body.includes('80.00 / 100'));
page=await reviewer('/index.php?page=interview_report&id=1');
assert.equal(page.status,200);assert(page.body.includes('面试通过报告'));assert(page.body.includes('测试甲'));assert(page.body.includes('测试通过'));assert(page.body.includes('window.print()'));assert(page.body.includes('@media print'));assert(!page.body.includes('<nav'));
assert.equal((await admin('/index.php?page=interview_report&id=2')).status,404,'unapproved candidate has no report');
page=await admin('/index.php?page=interview_results');assert(page.body.includes('80.00 / 100'));assert(!page.body.includes(' / 5</strong>'));
const saved=fixture('report-snapshot');assert.equal(saved.snapshot.score,4);
page=await admin('/index.php?page=interview_report&id=1');assert(page.body.includes('80.00 / 100'),'report must retain approved scores after changes');
console.log('PASS: full assessment/interview/review flow, admission gate, report snapshot, permissions, new-tab link, print styles, repeat assessment');
