<?php
function admin_header(string $title, string $active='dashboard'): void {
 $u=admin_user(); $flash=take_flash(); $modalRoute=isset($_GET['new'])||isset($_GET['edit']);$assetVersion=(string)max((int)@filemtime(ROOT_PATH.'/public/assets/app.css'),(int)@filemtime(ROOT_PATH.'/public/assets/extra.css'),(int)@filemtime(ROOT_PATH.'/public/assets/app.js'));
?><!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title><?=e($title)?> · 任职管理</title><link rel="stylesheet" href="/assets/app.css?v=<?=$assetVersion?>"><link rel="stylesheet" href="/assets/extra.css?v=<?=$assetVersion?>"><?php if($modalRoute):?><style>body.modal-route .split>form.form-panel{visibility:hidden!important}</style><?php endif;?><script src="/assets/qrcode.min.js" defer></script><script src="/assets/app.js?v=<?=$assetVersion?>" defer></script></head><body class="<?=$modalRoute?'modal-route':''?>"><a class="skip-link" href="#main-content">跳到主要内容</a>
<div class="shell"><aside class="sidebar"><a class="brand" href="/index.php"><img class="sidebar-wordmark" src="/assets/sanqi-3q-alpha.png" alt="3Q"><span><b>任职管理</b><small>RENZHI MANAGEMENT</small></span></a>
<nav><label>管理中心</label><?=nav_link('dashboard','工作台','▦',$active)?><?=nav_link('posts','职位管理','▣',$active)?><?=nav_link('standards','基本题目','◫',$active)?><?=nav_link('questions','题库管理','≡',$active)?><?=nav_link('preregister','测评登记','◎',$active)?><?=nav_link('manual','人工评分','✎',$active)?><?=nav_link('talent','人才审核','✓',$active)?><?=nav_link('talent_pool','人才库','♙',$active)?><?=nav_link('interviews','面试管理','◇',$active)?><?=nav_link('interview_results','面试结果','⌗',$active)?><label>系统设置</label><?=nav_link('users','用户管理','⚙',$active)?><?=nav_link('settings','系统配置','◉',$active)?><?=nav_link('logs','操作日志','⌁',$active)?></nav>
<div class="account"><span><?=e(first_char($u['real_name']??'管'))?></span><div><b><?=e($u['real_name']??'管理员')?></b><small><?=e(role_label($u['role']??'admin'))?></small></div><a href="?action=logout">退出</a></div></aside>
<main class="workspace"><header class="topbar"><form novalidate class="global-search" role="search" action="/index.php" method="get"><input type="hidden" name="page" value="talent"><span aria-hidden="true">⌕</span><input name="q" aria-label="搜索候选人" placeholder="搜索候选人姓名、手机号…"></form><div><?=date('Y年m月d日')?>　<span class="bell" aria-hidden="true">●</span></div></header><section class="content" id="main-content" tabindex="-1">
<?php if($flash):?><div class="flash <?=$flash[1]==='error'?'error':''?>" role="<?=$flash[1]==='error'?'alert':'status'?>" aria-live="polite"><?=e($flash[0])?></div><?php endif;?><div id="app-live-region" class="sr-only" aria-live="polite" aria-atomic="true"></div>
<?php }
function admin_footer(): void { ?></section></main></div></body></html><?php }
function nav_link(string $page,string $label,string $icon,string $active): string { $role=admin_user()['role']??'';$allowed=['admin'=>['dashboard','posts','standards','questions','preregister','manual','talent','talent_pool','interviews','interview_results','users','settings','logs'],'hr'=>['dashboard','posts','standards','questions','preregister','manual','talent','talent_pool','interviews','interview_results','users'],'leader'=>['dashboard','talent','talent_pool','interview_results']];if(!in_array($page,$allowed[$role]??[],true))return ''; $c=$page===$active?'active':''; return '<a class="'.$c.'" href="/index.php?page='.$page.'"><i>'.$icon.'</i><span>'.$label.'</span></a>'; }
function page_head(string $eyebrow,string $title,string $desc,string $action=''): void { ?><div class="page-head"><div><small><?=e($eyebrow)?></small><h1><?=e($title)?></h1><p><?=e($desc)?></p></div><?=$action?></div><?php }
function status_badge(string $status): string { $map=['recruiting'=>['招聘中','green'],'reserve'=>['储备中','gray'],'stop'=>['已停止','red'],'registered'=>['已登记','blue'],'scheduled'=>['已安排面试','green'],'verified'=>['已验证','amber'],'answered'=>['已答题','green'],'canceled'=>['已取消','gray'],'pending'=>['待处理','amber'],'first_pass'=>['初审通过','blue'],'first_reject'=>['不予推荐','red'],'interview'=>['面试中','blue'],'final_pass'=>['已录用','green'],'final_reject'=>['终审未通过','red'],'done'=>['已完成','green'],'scoring'=>['评分中','blue'],'published'=>['已发布','green'],'draft'=>['草稿','amber'],'retired'=>['已归档','gray'],'enabled'=>['已启用','green'],'disabled'=>['已停用','red']]; $v=$map[$status]??['未知状态','gray']; return '<span class="badge '.$v[1].'">'.$v[0].'</span>'; }
function role_label(string $role): string { return ['admin'=>'系统管理员','hr'=>'人力资源审核员','leader'=>'分管领导','interviewer'=>'面试官'][$role]??$role; }
function question_type_label(string $type): string { return ['single'=>'单选题','multi'=>'多选题','short'=>'简答题'][$type]??$type; }
function rule_type_label(string $type): string { return ['eq'=>'等于','range'=>'数值区间','in'=>'枚举集合','bool_range'=>'身份与年限'][$type]??$type; }
function action_label(string $action): string { $map=['post_save'=>'保存岗位','post_token_rotate'=>'轮换应聘码','pre_register'=>'新增预登记','pre_register_bulk'=>'批量预登记','pre_register_file'=>'文件导入预登记','pre_register_cancel'=>'取消预登记','pre_register_change_post'=>'应聘者改岗','standard_save'=>'保存评分标准','standard_publish'=>'发布评分标准','suzhi_item_save'=>'保存素质维度','question_save'=>'新增专业题','question_update'=>'编辑专业题','question_delete'=>'删除专业题','question_toggle'=>'启停专业题','question_set_publish'=>'发布题卷','manual_score'=>'人工评分','review_first'=>'人才初审','review_final'=>'人才终审','interview_session_create'=>'创建面试场次','interviewer_assign'=>'分配面试官','candidate_assign'=>'分配候选人','interview_session_status'=>'更新场次状态','interview_token_rotate'=>'轮换面试码','interview_assignment_remove'=>'移除场次人员','interview_score_reset'=>'重置面试评分','user_create'=>'创建用户','user_toggle'=>'启停用户','password_change'=>'修改密码','settings_save'=>'保存系统配置','database_backup'=>'数据库备份','export_preregister'=>'导出预登记','export_talent'=>'导出人才','export_interview_results'=>'导出面试结果','answer_submit'=>'提交应聘答卷'];return $map[$action]??$action; }
function review_label(string $value): string { return ['first'=>'初审','final'=>'终审','first_pass'=>'初审通过','first_reject'=>'初审不通过','final_pass'=>'终审录用','final_reject'=>'终审不录用'][$value]??$value; }
function h5_header(string $title): void { ?><!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title)?></title><link rel="stylesheet" href="/assets/app.css"><link rel="stylesheet" href="/assets/extra.css"></head><body class="h5-body"><main class="h5"><header class="h5-brand"><i>任</i><b><?=e($title)?></b></header><script>document.addEventListener('DOMContentLoaded',function(){var input=document.querySelector('input[name="birth_date"]');if(!input){return;}var initial=input.value?input.value.split('-'):[];var now=new Date();var wrap=document.createElement('div');wrap.className='birth-date-selects';var makeSelect=function(label,values,value){var select=document.createElement('select');select.required=true;select.setAttribute('aria-label',label);var empty=document.createElement('option');empty.value='';empty.textContent=label;select.appendChild(empty);values.forEach(function(item){var option=document.createElement('option');option.value=String(item);option.textContent=String(item)+(label==='年份'?'年':label==='月份'?'月':'日');if(String(item)===String(value)){option.selected=true;}select.appendChild(option);});return select;};var years=[];for(var year=now.getFullYear();year>=1940;year--){years.push(year);}var months=[];for(var month=1;month<=12;month++){months.push(month);}var days=[];for(var day=1;day<=31;day++){days.push(day);}var yearSelect=makeSelect('年份',years,initial[0]);var monthSelect=makeSelect('月份',months,initial[1]?Number(initial[1]):'');var daySelect=makeSelect('日期',days,initial[2]?Number(initial[2]):'');var update=function(){var y=yearSelect.value,m=monthSelect.value,d=daySelect.value;var max=y&&m?new Date(Number(y),Number(m),0).getDate():31;Array.prototype.forEach.call(daySelect.options,function(option){if(option.value){option.disabled=Number(option.value)>max;}});if(d&&Number(d)>max){daySelect.value='';d='';}input.value=y&&m&&d?y+'-'+String(m).padStart(2,'0')+'-'+String(d).padStart(2,'0'):'';};[yearSelect,monthSelect,daySelect].forEach(function(select){select.addEventListener('change',update);});input.type='hidden';input.required=false;wrap.append(yearSelect,monthSelect,daySelect);input.insertAdjacentElement('afterend',wrap);update();});</script><?php }
function h5_footer(): void { ?></main><script src="/assets/h5.js"></script></body></html><?php }
